security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, CAN_VIEW_NON_PUBLISHED]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user: { password: user, roles: [ 'ROLE_USER' ] }
                    jva:  { password: j4um3v1d4l, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Area administrador"
            logout:
                path:   /logout
                target: /

    access_control:
        # Devel public part
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Admin public part
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Secured part of the site
        - { path: ^/login, roles: ROLE_ADMIN }
        - { path: ^/add-page$, roles: ROLE_ADMIN }
        - { path: ^/remove-page$, roles: ROLE_ADMIN }
        # Public part
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
