security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, CAN_VIEW_NON_PUBLISHED]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user: { password: user, roles: [ 'ROLE_USER' ] }
                    jva:  { password: j4um3v1d4l, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Area administrador"
            logout:
                path:   /logout
                target: /

    access_control:
        #- { path: ^(/(de|fr|en))?/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: ROLE_ADMIN }
        #- { path: ^/efconnect, role: ROLE_USER }
        #- { path: ^/elfinder, role: ROLE_USER }
        